

services:
  laravel:
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    networks:
      - app-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vetdb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - GENERIC_TIMEZONE=America/Mexico_City
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - app-net
    restart: unless-stopped

  frontend:
    build:
      context: ./vetpet-main-front
      args:
        VITE_CHATBOT_URL: "http://n8n:5678/webhook/chatbot"
    environment:
      VITE_CHATBOT_URL: "http://n8n:5678/webhook/chatbot"
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-net

volumes:
  mysql_data:
  botpress_data:
  n8n_data:

networks:
  app-net:
